version: '3.9'

services:
  app:
    image: ubuntu:20.04  # Utilisation d'une version plus récente d'Ubuntu
    container_name: sentrifugo_app
    ports:
      - "80:80"  # Exposition du port 80 pour accéder à l'application via un navigateur web
    volumes:
      - ./sentrifugo:/var/www/html  # Montage d'un volume pour persister les données de Sentrifugo
    command: /bin/bash -c "apt-get update && 
                           DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common && 
                           add-apt-repository ppa:ondrej/php && 
                           apt-get update && 
                           apt-get install -y php7.4 php7.4-fpm php7.4-mysql php7.4-gd nginx unzip wget && 
                           mkdir -p /var/log/supervisor /run/php /etc/nginx /var/log/sentrifugo && 
                           echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && 
                           wget http://www.sentrifugo.com/home/downloadfile?file_name=Sentrifugo.zip -O Sentrifugo.zip && 
                           unzip Sentrifugo.zip -d /var/www/html && 
                           rm -rf Sentrifugo.zip && 
                           mv /var/www/html/Sentrifugo_3.0 /var/www/html/sentrifugo && 
                           chown -R www-data:www-data /var/www/html/sentrifugo && 
                           service php7.4-fpm start && 
                           service nginx start && 
                           /bin/bash"  # Cette commande configure l'environnement, installe Sentrifugo et démarre les services nécessaires
